using System;
using System.Collections.Generic;
using UnityEngine;
using GameFunctions;

namespace GameFunctions.Sample
{
    [GFBufferEncoderMessage]
    public struct MyExtraModel : IGFBufferEncoderMessage<MyExtraModel>
    {
        public bool boolValue;
        public bool[] boolArr;
        public List<bool> boolList;
        public byte byteValue;
        public byte[] byteArr;
        public List<byte> byteList;
        public sbyte sbyteValue;
        public sbyte[] sbyteArr;
        public List<sbyte> sbyteList;
        public short shortValue;
        public short[] shortArr;
        public List<short> shortList;
        public ushort ushortValue;
        public ushort[] ushortArr;
        public List<ushort> ushortList;
        public int intValue;
        public int[] intArr;
        public List<int> intList;
        public uint uintValue;
        public uint[] uintArr;
        public List<uint> uintList;
        public long longValue;
        public long[] longArr;
        public List<long> longList;
        public ulong ulongValue;
        public ulong[] ulongArr;
        public List<ulong> ulongList;
        public float floatValue;
        public float[] floatArr;
        public List<float> floatList;
        public double doubleValue;
        public double[] doubleArr;
        public List<double> doubleList;
        public char charValue;
        public string strValue;
        public string[] strArr;
        public List<string> strList;
        public HerExtraModel herModel;
        public HerExtraModel[] herModelArr;
        public List<HerExtraModel> herModelList;
        public string otherStr;
        public Vector2 vector2;
        public Vector2[] vector2Arr;
        public List<Vector2> vector2List;
        public Vector2Int vector2Int;
        public Vector2Int[] vector2IntArr;
        public List<Vector2Int> vector2IntList;
        public Vector3 vector3;
        public Vector3[] vector3Arr;
        public List<Vector3> vector3List;
        public Vector3Int vector3Int;
        public Vector3Int[] vector3IntArr;
        public List<Vector3Int> vector3IntList;
        public Vector4 vector4;
        public Vector4[] vector4Arr;
        public List<Vector4> vector4List;
        public Quaternion quaternion;
        public Quaternion[] quaternionArr;
        public List<Quaternion> quaternionList;
        public Color color;
        public Color[] colorArr;
        public List<Color> colorList;
        public Color32 color32;
        public Color32[] color32Arr;
        public List<Color32> color32List;
        public Rect rect;
        public Rect[] rectArr;
        public List<Rect> rectList;
        public void WriteTo(byte[] dst, ref int offset)
        {
            GFBufferEncoderWriter.WriteBool(dst, boolValue, ref offset);
            GFBufferEncoderWriter.WriteBoolArr(dst, boolArr, ref offset);
            GFBufferEncoderWriter.WriteBoolList(dst, boolList, ref offset);
            GFBufferEncoderWriter.WriteUInt8(dst, byteValue, ref offset);
            GFBufferEncoderWriter.WriteUint8Arr(dst, byteArr, ref offset);
            GFBufferEncoderWriter.WriteUint8List(dst, byteList, ref offset);
            GFBufferEncoderWriter.WriteInt8(dst, sbyteValue, ref offset);
            GFBufferEncoderWriter.WriteInt8Arr(dst, sbyteArr, ref offset);
            GFBufferEncoderWriter.WriteInt8List(dst, sbyteList, ref offset);
            GFBufferEncoderWriter.WriteInt16(dst, shortValue, ref offset);
            GFBufferEncoderWriter.WriteInt16Arr(dst, shortArr, ref offset);
            GFBufferEncoderWriter.WriteInt16List(dst, shortList, ref offset);
            GFBufferEncoderWriter.WriteUInt16(dst, ushortValue, ref offset);
            GFBufferEncoderWriter.WriteUInt16Arr(dst, ushortArr, ref offset);
            GFBufferEncoderWriter.WriteUInt16List(dst, ushortList, ref offset);
            GFBufferEncoderWriter.WriteInt32(dst, intValue, ref offset);
            GFBufferEncoderWriter.WriteInt32Arr(dst, intArr, ref offset);
            GFBufferEncoderWriter.WriteInt32List(dst, intList, ref offset);
            GFBufferEncoderWriter.WriteUInt32(dst, uintValue, ref offset);
            GFBufferEncoderWriter.WriteUInt32Arr(dst, uintArr, ref offset);
            GFBufferEncoderWriter.WriteUInt32List(dst, uintList, ref offset);
            GFBufferEncoderWriter.WriteInt64(dst, longValue, ref offset);
            GFBufferEncoderWriter.WriteInt64Arr(dst, longArr, ref offset);
            GFBufferEncoderWriter.WriteInt64List(dst, longList, ref offset);
            GFBufferEncoderWriter.WriteUInt64(dst, ulongValue, ref offset);
            GFBufferEncoderWriter.WriteUInt64Arr(dst, ulongArr, ref offset);
            GFBufferEncoderWriter.WriteUInt64List(dst, ulongList, ref offset);
            GFBufferEncoderWriter.WriteSingle(dst, floatValue, ref offset);
            GFBufferEncoderWriter.WriteSingleArr(dst, floatArr, ref offset);
            GFBufferEncoderWriter.WriteSingleList(dst, floatList, ref offset);
            GFBufferEncoderWriter.WriteDouble(dst, doubleValue, ref offset);
            GFBufferEncoderWriter.WriteDoubleArr(dst, doubleArr, ref offset);
            GFBufferEncoderWriter.WriteDoubleList(dst, doubleList, ref offset);
            GFBufferEncoderWriter.WriteChar(dst, charValue, ref offset);
            GFBufferEncoderWriter.WriteUTF8String(dst, strValue, ref offset);
            GFBufferEncoderWriter.WriteUTF8StringArr(dst, strArr, ref offset);
            GFBufferEncoderWriter.WriteUTF8StringList(dst, strList, ref offset);
            GFBufferEncoderWriter.WriteMessage(dst, herModel, ref offset);
            GFBufferEncoderWriter.WriteMessageArr(dst, herModelArr, ref offset);
            GFBufferEncoderWriter.WriteMessageList(dst, herModelList, ref offset);
            GFBufferEncoderWriter.WriteUTF8String(dst, otherStr, ref offset);
            GFBufferEncoderWriter.WriteVector2(dst, vector2, ref offset);
            GFBufferEncoderWriter.WriteVector2Array(dst, vector2Arr, ref offset);
            GFBufferEncoderWriter.WriteVector2List(dst, vector2List, ref offset);
            GFBufferEncoderWriter.WriteVector2Int(dst, vector2Int, ref offset);
            GFBufferEncoderWriter.WriteVector2IntArray(dst, vector2IntArr, ref offset);
            GFBufferEncoderWriter.WriteVector2IntList(dst, vector2IntList, ref offset);
            GFBufferEncoderWriter.WriteVector3(dst, vector3, ref offset);
            GFBufferEncoderWriter.WriteVector3Array(dst, vector3Arr, ref offset);
            GFBufferEncoderWriter.WriteVector3List(dst, vector3List, ref offset);
            GFBufferEncoderWriter.WriteVector3Int(dst, vector3Int, ref offset);
            GFBufferEncoderWriter.WriteVector3IntArray(dst, vector3IntArr, ref offset);
            GFBufferEncoderWriter.WriteVector3IntList(dst, vector3IntList, ref offset);
            GFBufferEncoderWriter.WriteVector4(dst, vector4, ref offset);
            GFBufferEncoderWriter.WriteVector4Array(dst, vector4Arr, ref offset);
            GFBufferEncoderWriter.WriteVector4List(dst, vector4List, ref offset);
            GFBufferEncoderWriter.WriteQuaternion(dst, quaternion, ref offset);
            GFBufferEncoderWriter.WriteQuaternionArray(dst, quaternionArr, ref offset);
            GFBufferEncoderWriter.WriteQuaternionList(dst, quaternionList, ref offset);
            GFBufferEncoderWriter.WriteColor(dst, color, ref offset);
            GFBufferEncoderWriter.WriteColorArray(dst, colorArr, ref offset);
            GFBufferEncoderWriter.WriteColorList(dst, colorList, ref offset);
            GFBufferEncoderWriter.WriteColor32(dst, color32, ref offset);
            GFBufferEncoderWriter.WriteColor32Array(dst, color32Arr, ref offset);
            GFBufferEncoderWriter.WriteColor32List(dst, color32List, ref offset);
            GFBufferEncoderWriter.WriteRect(dst, rect, ref offset);
            GFBufferEncoderWriter.WriteRectArray(dst, rectArr, ref offset);
            GFBufferEncoderWriter.WriteRectList(dst, rectList, ref offset);
        }

        public void FromBytes(byte[] src, ref int offset)
        {
            boolValue = GFBufferEncoderReader.ReadBool(src, ref offset);
            boolArr = GFBufferEncoderReader.ReadBoolArr(src, ref offset);
            boolList = GFBufferEncoderReader.ReadBoolList(src, ref offset);
            byteValue = GFBufferEncoderReader.ReadUInt8(src, ref offset);
            byteArr = GFBufferEncoderReader.ReadUInt8Arr(src, ref offset);
            byteList = GFBufferEncoderReader.ReadUInt8List(src, ref offset);
            sbyteValue = GFBufferEncoderReader.ReadInt8(src, ref offset);
            sbyteArr = GFBufferEncoderReader.ReadInt8Arr(src, ref offset);
            sbyteList = GFBufferEncoderReader.ReadInt8List(src, ref offset);
            shortValue = GFBufferEncoderReader.ReadInt16(src, ref offset);
            shortArr = GFBufferEncoderReader.ReadInt16Arr(src, ref offset);
            shortList = GFBufferEncoderReader.ReadInt16List(src, ref offset);
            ushortValue = GFBufferEncoderReader.ReadUInt16(src, ref offset);
            ushortArr = GFBufferEncoderReader.ReadUInt16Arr(src, ref offset);
            ushortList = GFBufferEncoderReader.ReadUInt16List(src, ref offset);
            intValue = GFBufferEncoderReader.ReadInt32(src, ref offset);
            intArr = GFBufferEncoderReader.ReadInt32Arr(src, ref offset);
            intList = GFBufferEncoderReader.ReadInt32List(src, ref offset);
            uintValue = GFBufferEncoderReader.ReadUInt32(src, ref offset);
            uintArr = GFBufferEncoderReader.ReadUInt32Arr(src, ref offset);
            uintList = GFBufferEncoderReader.ReadUInt32List(src, ref offset);
            longValue = GFBufferEncoderReader.ReadInt64(src, ref offset);
            longArr = GFBufferEncoderReader.ReadInt64Arr(src, ref offset);
            longList = GFBufferEncoderReader.ReadInt64List(src, ref offset);
            ulongValue = GFBufferEncoderReader.ReadUInt64(src, ref offset);
            ulongArr = GFBufferEncoderReader.ReadUInt64Arr(src, ref offset);
            ulongList = GFBufferEncoderReader.ReadUInt64List(src, ref offset);
            floatValue = GFBufferEncoderReader.ReadSingle(src, ref offset);
            floatArr = GFBufferEncoderReader.ReadSingleArr(src, ref offset);
            floatList = GFBufferEncoderReader.ReadSingleList(src, ref offset);
            doubleValue = GFBufferEncoderReader.ReadDouble(src, ref offset);
            doubleArr = GFBufferEncoderReader.ReadDoubleArr(src, ref offset);
            doubleList = GFBufferEncoderReader.ReadDoubleList(src, ref offset);
            charValue = GFBufferEncoderReader.ReadChar(src, ref offset);
            strValue = GFBufferEncoderReader.ReadUTF8String(src, ref offset);
            strArr = GFBufferEncoderReader.ReadUTF8StringArr(src, ref offset);
            strList = GFBufferEncoderReader.ReadUTF8StringList(src, ref offset);
            herModel = GFBufferEncoderReader.ReadMessage(src, () => new HerExtraModel(), ref offset);
            herModelArr = GFBufferEncoderReader.ReadMessageArr(src, () => new HerExtraModel(), ref offset);
            herModelList = GFBufferEncoderReader.ReadMessageList(src, () => new HerExtraModel(), ref offset);
            otherStr = GFBufferEncoderReader.ReadUTF8String(src, ref offset);
            vector2 = GFBufferEncoderReader.ReadVector2(src, ref offset);
            vector2Arr = GFBufferEncoderReader.ReadVector2Array(src, ref offset);
            vector2List = GFBufferEncoderReader.ReadVector2List(src, ref offset);
            vector2Int = GFBufferEncoderReader.ReadVector2Int(src, ref offset);
            vector2IntArr = GFBufferEncoderReader.ReadVector2IntArray(src, ref offset);
            vector2IntList = GFBufferEncoderReader.ReadVector2IntList(src, ref offset);
            vector3 = GFBufferEncoderReader.ReadVector3(src, ref offset);
            vector3Arr = GFBufferEncoderReader.ReadVector3Array(src, ref offset);
            vector3List = GFBufferEncoderReader.ReadVector3List(src, ref offset);
            vector3Int = GFBufferEncoderReader.ReadVector3Int(src, ref offset);
            vector3IntArr = GFBufferEncoderReader.ReadVector3IntArray(src, ref offset);
            vector3IntList = GFBufferEncoderReader.ReadVector3IntList(src, ref offset);
            vector4 = GFBufferEncoderReader.ReadVector4(src, ref offset);
            vector4Arr = GFBufferEncoderReader.ReadVector4Array(src, ref offset);
            vector4List = GFBufferEncoderReader.ReadVector4List(src, ref offset);
            quaternion = GFBufferEncoderReader.ReadQuaternion(src, ref offset);
            quaternionArr = GFBufferEncoderReader.ReadQuaternionArray(src, ref offset);
            quaternionList = GFBufferEncoderReader.ReadQuaternionList(src, ref offset);
            color = GFBufferEncoderReader.ReadColor(src, ref offset);
            colorArr = GFBufferEncoderReader.ReadColorArray(src, ref offset);
            colorList = GFBufferEncoderReader.ReadColorList(src, ref offset);
            color32 = GFBufferEncoderReader.ReadColor32(src, ref offset);
            color32Arr = GFBufferEncoderReader.ReadColor32Array(src, ref offset);
            color32List = GFBufferEncoderReader.ReadColor32List(src, ref offset);
            rect = GFBufferEncoderReader.ReadRect(src, ref offset);
            rectArr = GFBufferEncoderReader.ReadRectArray(src, ref offset);
            rectList = GFBufferEncoderReader.ReadRectList(src, ref offset);
        }
    }
}